[project]
name = "comfyui-fluxtrainer"
description = "Currently supports LoRA training, and untested full finetune with code from kohya's scripts: [a/https://github.com/kohya-ss/sd-scripts](https://github.com/kohya-ss/sd-scripts)"
version = "1.0.1"
license = { file = "LICENSE" }
dependencies = [
    "accelerate>=0.33.0",
    "numpy<=1.26.4",
    "transformers>=4.44.0",
    "diffusers>=0.25.0",
    "ftfy>=6.1.1",
    "opencv-python>=4.7.0.68",
    "einops>=0.7.0",
    "bitsandbytes>=0.43.3",
    "prodigyopt>=1.0",
    "lion-pytorch>=0.0.6",
    "safetensors>=0.4.2",
    "altair>=4.2.2",
    "toml>=0.10.2",
    "voluptuous>=0.13.1",
    "huggingface-hub>=0.24.5",
    "# for Image utils",
    "imagesize>=1.4.1",
    "rich>=13.7.0",
    "came_pytorch",
    "matplotlib",
    "# for T5XXL tokenizer (SD3/FLUX)",
    "sentencepiece>=0.2.0",
]

[project.urls]
Repository = "https://github.com/kijai/ComfyUI-FluxTrainer"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "kijai"
DisplayName = "ComfyUI-FluxTrainer"
Icon = ""
